"""add fitness_goal to user

Revision ID: 210e531f7c01
Revises: 785d1adf6e32
Create Date: 2026-06-02 01:58:22.340292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210e531f7c01'
down_revision = '785d1adf6e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=150), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitness_goal', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fitness_goal')

    op.drop_table('exercise_log')
    # ### end Alembic commands ###
