COMMON_FOODS = {
    # PROTEINS
    "egg": {"name": "Large Egg", "category": "Protein", "serving": "1 large egg", "calories": 72, "protein": 6.3, "carbs": 0.4, "fats": 5},
    "egg white": {"name": "Egg White", "category": "Protein", "serving": "1 egg white", "calories": 17, "protein": 3.6, "carbs": 0.2, "fats": 0},
    "chicken breast": {"name": "Chicken Breast", "category": "Protein", "serving": "100g cooked", "calories": 165, "protein": 31, "carbs": 0, "fats": 3.6},
    "chicken thigh": {"name": "Chicken Thigh", "category": "Protein", "serving": "100g cooked", "calories": 209, "protein": 26, "carbs": 0, "fats": 11},
    "turkey breast": {"name": "Turkey Breast", "category": "Protein", "serving": "100g cooked", "calories": 135, "protein": 30, "carbs": 0, "fats": 1},
    "lean ground beef": {"name": "Lean Ground Beef", "category": "Protein", "serving": "100g cooked", "calories": 217, "protein": 26, "carbs": 0, "fats": 12},
    "sirloin steak": {"name": "Sirloin Steak", "category": "Protein", "serving": "100g cooked", "calories": 206, "protein": 27, "carbs": 0, "fats": 10},
    "salmon": {"name": "Salmon", "category": "Protein", "serving": "100g cooked", "calories": 208, "protein": 22, "carbs": 0, "fats": 13},
    "tuna": {"name": "Tuna", "category": "Protein", "serving": "100g", "calories": 132, "protein": 29, "carbs": 0, "fats": 1},
    "tilapia": {"name": "Tilapia", "category": "Protein", "serving": "100g cooked", "calories": 128, "protein": 26, "carbs": 0, "fats": 2},
    "shrimp": {"name": "Shrimp", "category": "Protein", "serving": "100g cooked", "calories": 99, "protein": 24, "carbs": 0, "fats": 0.3},
    "cod": {"name": "Cod", "category": "Protein", "serving": "100g cooked", "calories": 105, "protein": 23, "carbs": 0, "fats": 1},
    "crab": {"name": "Crab", "category": "Protein", "serving": "100g cooked", "calories": 97, "protein": 21, "carbs": 0, "fats": 1},
    "pork loin": {"name": "Pork Loin", "category": "Protein", "serving": "100g cooked", "calories": 196, "protein": 27, "carbs": 0, "fats": 8},
    "ham": {"name": "Ham", "category": "Protein", "serving": "100g", "calories": 145, "protein": 21, "carbs": 1.5, "fats": 5},
    "tofu": {"name": "Tofu", "category": "Plant Protein", "serving": "100g", "calories": 76, "protein": 8, "carbs": 2, "fats": 4.8},
    "tempeh": {"name": "Tempeh", "category": "Plant Protein", "serving": "100g", "calories": 193, "protein": 20, "carbs": 9, "fats": 11},
    "protein powder": {"name": "Whey Protein", "category": "Protein", "serving": "1 scoop", "calories": 120, "protein": 24, "carbs": 3, "fats": 1.5},
    "greek yogurt": {"name": "Greek Yogurt", "category": "Protein", "serving": "170g container", "calories": 100, "protein": 17, "carbs": 6, "fats": 0},
    "cottage cheese": {"name": "Cottage Cheese", "category": "Protein", "serving": "100g", "calories": 98, "protein": 11, "carbs": 3, "fats": 4},

    # CARBS
    "rice": {"name": "White Rice", "category": "Carbohydrate", "serving": "1 cup cooked", "calories": 205, "protein": 4.3, "carbs": 45, "fats": 0.4},
    "brown rice": {"name": "Brown Rice", "category": "Carbohydrate", "serving": "1 cup cooked", "calories": 216, "protein": 5, "carbs": 45, "fats": 1.8},
    "jasmine rice": {"name": "Jasmine Rice", "category": "Carbohydrate", "serving": "1 cup cooked", "calories": 205, "protein": 4, "carbs": 45, "fats": 0.4},
    "basmati rice": {"name": "Basmati Rice", "category": "Carbohydrate", "serving": "1 cup cooked", "calories": 190, "protein": 4, "carbs": 41, "fats": 0.5},
    "sweet potato": {"name": "Sweet Potato", "category": "Carbohydrate", "serving": "1 medium", "calories": 112, "protein": 2, "carbs": 26, "fats": 0.1},
    "potato": {"name": "Potato", "category": "Carbohydrate", "serving": "1 medium", "calories": 161, "protein": 4, "carbs": 37, "fats": 0.2},
    "oatmeal": {"name": "Oatmeal", "category": "Carbohydrate", "serving": "1 cup cooked", "calories": 150, "protein": 5, "carbs": 27, "fats": 3},
    "quinoa": {"name": "Quinoa", "category": "Carbohydrate", "serving": "1 cup cooked", "calories": 222, "protein": 8, "carbs": 39, "fats": 3.6},
    "whole wheat bread": {"name": "Whole Wheat Bread", "category": "Carbohydrate", "serving": "1 slice", "calories": 110, "protein": 5, "carbs": 20, "fats": 1.5},
    "bagel": {"name": "Bagel", "category": "Carbohydrate", "serving": "1 medium bagel", "calories": 245, "protein": 10, "carbs": 48, "fats": 1.5},
    "tortilla": {"name": "Tortilla", "category": "Carbohydrate", "serving": "1 large tortilla", "calories": 140, "protein": 4, "carbs": 24, "fats": 3},
    "pasta": {"name": "Pasta", "category": "Carbohydrate", "serving": "1 cup cooked", "calories": 220, "protein": 8, "carbs": 43, "fats": 1.3},
    "whole wheat pasta": {"name": "Whole Wheat Pasta", "category": "Carbohydrate", "serving": "1 cup cooked", "calories": 174, "protein": 7.5, "carbs": 37, "fats": 1},
    "cereal": {"name": "Cereal", "category": "Carbohydrate", "serving": "1 cup", "calories": 120, "protein": 3, "carbs": 24, "fats": 1},
    "granola": {"name": "Granola", "category": "Carbohydrate", "serving": "1/2 cup", "calories": 220, "protein": 5, "carbs": 30, "fats": 9},

    # FRUITS
    "banana": {"name": "Banana", "category": "Fruit", "serving": "1 medium banana", "calories": 105, "protein": 1.3, "carbs": 27, "fats": 0.3},
    "apple": {"name": "Apple", "category": "Fruit", "serving": "1 medium apple", "calories": 95, "protein": 0.5, "carbs": 25, "fats": 0.3},
    "orange": {"name": "Orange", "category": "Fruit", "serving": "1 medium orange", "calories": 62, "protein": 1.2, "carbs": 15, "fats": 0.2},
    "pineapple": {"name": "Pineapple", "category": "Fruit", "serving": "1 cup", "calories": 82, "protein": 1, "carbs": 22, "fats": 0.2},
    "mango": {"name": "Mango", "category": "Fruit", "serving": "1 cup", "calories": 99, "protein": 1.4, "carbs": 25, "fats": 0.6},
    "watermelon": {"name": "Watermelon", "category": "Fruit", "serving": "1 cup", "calories": 46, "protein": 1, "carbs": 11, "fats": 0.2},
    "strawberries": {"name": "Strawberries", "category": "Fruit", "serving": "1 cup", "calories": 49, "protein": 1, "carbs": 12, "fats": 0.5},
    "blueberries": {"name": "Blueberries", "category": "Fruit", "serving": "1 cup", "calories": 84, "protein": 1, "carbs": 21, "fats": 0.5},
    "raspberries": {"name": "Raspberries", "category": "Fruit", "serving": "1 cup", "calories": 64, "protein": 1.5, "carbs": 15, "fats": 0.8},
    "grapes": {"name": "Grapes", "category": "Fruit", "serving": "1 cup", "calories": 104, "protein": 1, "carbs": 27, "fats": 0.2},

    # HEALTHY FATS
    "avocado": {"name": "Avocado", "category": "Healthy Fat", "serving": "1 medium avocado", "calories": 240, "protein": 3, "carbs": 13, "fats": 22},
    "almonds": {"name": "Almonds", "category": "Healthy Fat", "serving": "1 oz", "calories": 164, "protein": 6, "carbs": 6, "fats": 14},
    "walnuts": {"name": "Walnuts", "category": "Healthy Fat", "serving": "1 oz", "calories": 185, "protein": 4, "carbs": 4, "fats": 18},
    "cashews": {"name": "Cashews", "category": "Healthy Fat", "serving": "1 oz", "calories": 157, "protein": 5, "carbs": 9, "fats": 12},
    "peanut butter": {"name": "Peanut Butter", "category": "Healthy Fat", "serving": "2 tbsp", "calories": 190, "protein": 8, "carbs": 7, "fats": 16},
    "almond butter": {"name": "Almond Butter", "category": "Healthy Fat", "serving": "2 tbsp", "calories": 190, "protein": 7, "carbs": 6, "fats": 17},
    "olive oil": {"name": "Olive Oil", "category": "Healthy Fat", "serving": "1 tbsp", "calories": 119, "protein": 0, "carbs": 0, "fats": 14},
    "coconut oil": {"name": "Coconut Oil", "category": "Healthy Fat", "serving": "1 tbsp", "calories": 121, "protein": 0, "carbs": 0, "fats": 14},
    "chia seeds": {"name": "Chia Seeds", "category": "Healthy Fat", "serving": "1 oz", "calories": 138, "protein": 5, "carbs": 12, "fats": 9},
    "flax seeds": {"name": "Flax Seeds", "category": "Healthy Fat", "serving": "1 oz", "calories": 150, "protein": 5, "carbs": 8, "fats": 12},

    # VEGETABLES
    "broccoli": {"name": "Broccoli", "category": "Vegetable", "serving": "1 cup cooked", "calories": 55, "protein": 4, "carbs": 11, "fats": 0.6},
    "spinach": {"name": "Spinach", "category": "Vegetable", "serving": "100g", "calories": 23, "protein": 3, "carbs": 4, "fats": 0.4},
    "asparagus": {"name": "Asparagus", "category": "Vegetable", "serving": "1 cup", "calories": 27, "protein": 3, "carbs": 5, "fats": 0.2},
    "green beans": {"name": "Green Beans", "category": "Vegetable", "serving": "1 cup", "calories": 31, "protein": 2, "carbs": 7, "fats": 0.2},
    "carrots": {"name": "Carrots", "category": "Vegetable", "serving": "1 cup", "calories": 50, "protein": 1, "carbs": 12, "fats": 0.3},
    "cucumber": {"name": "Cucumber", "category": "Vegetable", "serving": "1 cup", "calories": 16, "protein": 1, "carbs": 4, "fats": 0.1},
    "lettuce": {"name": "Lettuce", "category": "Vegetable", "serving": "1 cup", "calories": 10, "protein": 1, "carbs": 2, "fats": 0.1},
    "tomato": {"name": "Tomato", "category": "Vegetable", "serving": "1 medium", "calories": 22, "protein": 1, "carbs": 5, "fats": 0.2},
    "bell pepper": {"name": "Bell Pepper", "category": "Vegetable", "serving": "1 medium", "calories": 31, "protein": 1, "carbs": 6, "fats": 0.3},
    "zucchini": {"name": "Zucchini", "category": "Vegetable", "serving": "1 cup", "calories": 20, "protein": 1.5, "carbs": 4, "fats": 0.3},

    # DAIRY
    "milk": {"name": "Milk", "category": "Dairy", "serving": "1 cup", "calories": 122, "protein": 8, "carbs": 12, "fats": 5},
    "skim milk": {"name": "Skim Milk", "category": "Dairy", "serving": "1 cup", "calories": 83, "protein": 8, "carbs": 12, "fats": 0},
    "cheddar cheese": {"name": "Cheddar Cheese", "category": "Dairy", "serving": "1 oz", "calories": 113, "protein": 7, "carbs": 1, "fats": 9},
    "mozzarella": {"name": "Mozzarella", "category": "Dairy", "serving": "1 oz", "calories": 85, "protein": 6, "carbs": 1, "fats": 6},
    "parmesan": {"name": "Parmesan", "category": "Dairy", "serving": "1 oz", "calories": 110, "protein": 10, "carbs": 1, "fats": 7},

    # FITNESS SNACKS
    "protein bar": {"name": "Protein Bar", "category": "Fitness Snack", "serving": "1 bar", "calories": 200, "protein": 20, "carbs": 22, "fats": 7},
    "rice cakes": {"name": "Rice Cakes", "category": "Fitness Snack", "serving": "1 cake", "calories": 35, "protein": 1, "carbs": 7, "fats": 0},
    "beef jerky": {"name": "Beef Jerky", "category": "Fitness Snack", "serving": "1 oz", "calories": 116, "protein": 9, "carbs": 3, "fats": 7},
    "popcorn": {"name": "Popcorn", "category": "Fitness Snack", "serving": "3 cups air-popped", "calories": 93, "protein": 3, "carbs": 19, "fats": 1},
    "dark chocolate": {"name": "Dark Chocolate", "category": "Fitness Snack", "serving": "1 oz", "calories": 170, "protein": 2, "carbs": 13, "fats": 12}
}